// Auto-generated from the SusTerm Dictionary PDF — Difficult set.
// Examples are rephrased (not just blanked verbatim) into fresh scenario
// framings, with the term hashed out as "........" and turned into a
// question when the blank lands at the end. `definition` is shown after a
// wrong answer. Split into batches so a session isn't 50+ questions long.
import { Option, Level } from "@prisma/client";

export const susTermDifficultQuestions: {
  text: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: Option;
  definition: string;
  level: Level;
  batch: number;
}[] = [
  // --- Batch 1 (15 questions) ---
  {
    text: "Picture this: in 2022, bad droughts in Africa and Europe caused shortages of wheat, leading to higher prices for bread; a clear case of ........?",
    optionA: "Biogenic Carbon Emissions",
    optionB: "Agflation",
    optionC: "Nationally Determined Contributions (NDCS)",
    optionD: "Internal Carbon Pricing",
    correctOption: "B",
    definition: "Agflation means the rising prices of food and agricultural products because of problems like bad weather, droughts, or climate change. When crops fail, food becomes more expensive for everyone.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Here's a real-world case: farmers in Australia use ........ to make their soils more fertile and lock carbon into the ground instead of letting it go into the air.",
    optionA: "Green Cloud",
    optionB: "Agrichar",
    optionC: "Insetting",
    optionD: "Environmental Impact Assessment (EIA)",
    correctOption: "B",
    definition: "Agrichar is a type of charcoal made from plant materials like crops, leaves, and wood, through a special process called pyrolysis (heating without oxygen). It can be added to soil to improve farming and store carbon for a long time, helping to fight climate change.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Take this example: the use of cars, factories, and airplanes has increased greenhouse gases in the atmosphere, leading to ........?",
    optionA: "Anthropogenic Climate Change",
    optionB: "Net Zero",
    optionC: "Biogenic Carbon Emissions",
    optionD: "Deep Retrofit",
    correctOption: "A",
    definition: "Anthropogenic climate change refers to the changes in the Earth’s climate that are caused by human activities, such as burning fossil fuels (coal, oil, and gas), cutting down forests, and farming.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Here's how it plays out: a company that installs machines to suck carbon dioxide from the air and store it underground is contributing to ........?",
    optionA: "Blue Financial Instruments",
    optionB: "Carbon Insetting",
    optionC: "Downcycling",
    optionD: "Anthropogenic Removals",
    correctOption: "D",
    definition: "Anthropogenic removals are actions taken by humans to remove greenhouse gases from the atmosphere. This includes techniques like planting trees, which absorb carbon dioxide, or using technologies like carbon capture and storage to directly remove gases from the air.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "By installing solar panels instead of using coal-fired electricity, a city avoids emissions that would have contributed to climate change.",
    optionA: "Biogenic Carbon Emissions",
    optionB: "Avoided Emissions",
    optionC: "Internal Carbon Pricing",
    optionD: "Nationally Determined Contributions (NDCS)",
    correctOption: "B",
    definition: "Avoided emissions are the amount of greenhouse gases that are not released into the atmosphere because a cleaner, more sustainable option was chosen.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Burning wood logs in a fireplace releases biogenic carbon, which was initially absorbed by the tree during its growth.",
    optionA: "Internal Carbon Pricing",
    optionB: "Decarbonisation",
    optionC: "Blackwater",
    optionD: "Biogenic Carbon Emissions",
    correctOption: "D",
    definition: "These are carbon dioxide (CO₂) emissions originating from natural, organic sources such as plants and animals, rather than fossil fuels.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Velcro was inspired by how burrs stick to animal fur, showing how nature can guide practical invention.",
    optionA: "Agflation",
    optionB: "Negative Screening",
    optionC: "Biomimicry",
    optionD: "Green Cloud",
    correctOption: "C",
    definition: "Biomimicry is an approach to innovation that seeks solutions by emulating nature’s designs and processes.It helps create sustainable and efficient technologies by learning from biological systems.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Consider this scenario: people often feel more relaxed and focused when they spend time in green spaces like parks or forests, due to ........?",
    optionA: "Agflation",
    optionB: "Blue Financial Instruments",
    optionC: "Biophilia",
    optionD: "End-of-life Scenario",
    correctOption: "C",
    definition: "Biophilia is the idea that humans have an innate connection to nature and a desire to be close to natural environments.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Think about it this way: an office that includes indoor gardens, large windows for natural sunlight, and flowing water features uses ........?",
    optionA: "Biophilic Design",
    optionB: "Positive Screening",
    optionC: "Green Hushing",
    optionD: "Blackwater",
    correctOption: "A",
    definition: "Biophilic design involves incorporating natural elements such as plants, natural light, water features, and organic materials into buildings and workspaces to improve occupant well-being and productivity.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Here's how it plays out: in a building with separate plumbing systems, ........ from toilets is sent to a treatment facility, while greywater from showers is reused for irrigation.",
    optionA: "Feed-in Tariff",
    optionB: "Blackwater",
    optionC: "Avoided Emissions",
    optionD: "Carbon Sequestration",
    correctOption: "B",
    definition: "Blackwater is wastewater that contains human waste, typically from toilets.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "A government issues blue bonds to finance coral reef protection and sustainable fisheries in its coastal regions.",
    optionA: "Biomimicry",
    optionB: "Embedded Water",
    optionC: "Blue Financial Instruments",
    optionD: "Insetting",
    correctOption: "C",
    definition: "These are financial products like blue bonds or blue loans designed to fund sustainable marine and ocean-related projects.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "A coffee company planting trees on the farms it sources beans from to reduce emissions is doing insetting.",
    optionA: "Carbon Insetting",
    optionB: "Embedded Water",
    optionC: "Green Lashing",
    optionD: "Blue Financial Instruments",
    correctOption: "A",
    definition: "Reducing carbon emissions inside a company’s own value chain, rather than paying for offsets elsewhere.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Buying a carbon offset for a flight funds a wind farm elsewhere to balance the plane’s emissions.",
    optionA: "Positive Screening",
    optionB: "Carbon Offsetting",
    optionC: "Product Carbon Footprint",
    optionD: "Climate Shadow",
    correctOption: "B",
    definition: "Paying for activities that reduce emissions (like tree planting or renewable energy) to cancel out your own emissions.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Here's a real-world case: if a country tightens emission rules and companies move factories to countries with looser rules, that’s ........?",
    optionA: "Decarbonisation",
    optionB: "Embedded Carbon",
    optionC: "Agrichar",
    optionD: "Carbon Leakage",
    correctOption: "D",
    definition: "When efforts to reduce emissions in one place cause emissions to increase somewhere else.",
    level: "DIFFICULT",
    batch: 1,
  },
  {
    text: "Trees naturally sequester CO₂ by absorbing it during photosynthesis and storing it in their trunks and roots.",
    optionA: "Scopes of Emission",
    optionB: "Global Warming Potential (GWP)",
    optionC: "Carbon Sequestration",
    optionD: "Carbon Offsetting",
    correctOption: "C",
    definition: "Capturing and storing carbon dioxide so it doesn’t enter the atmosphere.",
    level: "DIFFICULT",
    batch: 1,
  },
  // --- Batch 2 (15 questions) ---
  {
    text: "Here's a case worth knowing: someone might reduce their personal emissions but still support high-emission industries, creating a large ........?",
    optionA: "Biophilic Design",
    optionB: "Anthropogenic Removals",
    optionC: "Embedded Carbon",
    optionD: "Climate Shadow",
    correctOption: "D",
    definition: "A broader look at how someone’s actions—beyond just carbon use —affect the climate, including what they vote for, fund, or support.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Picture this: in a ........, plastic bottles are collected, melted, and used to make new bottles.",
    optionA: "Closed Loop",
    optionB: "Green Hushing",
    optionC: "Insetting",
    optionD: "Biophilic Design",
    correctOption: "A",
    definition: "A system where resources are reused or recycled instead of being wasted, aiming for zero waste.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "A company analyzing emissions from mining to factory delivery is using a cradle-to-gate assessment.",
    optionA: "Carbon Insetting",
    optionB: "Net Zero",
    optionC: "Cradle to Gate",
    optionD: "Feed-in Tariff",
    correctOption: "C",
    definition: "Measuring a product’s environmental impact from the raw material stage to when it leaves the factory (not including shipping or use).",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Think about it this way: switching from coal to solar power is part of a country's ........ plan.",
    optionA: "Green Lashing",
    optionB: "Internal Carbon Pricing",
    optionC: "Double Materiality Assessment",
    optionD: "Decarbonisation",
    correctOption: "D",
    definition: "Reducing or eliminating carbon emissions from activities like energy, transport, or manufacturing.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Take this example: adding insulation, solar panels, and smart heating in an old home is a ........?",
    optionA: "Cradle to Gate",
    optionB: "Carbon Offsetting",
    optionC: "Deep Retrofit",
    optionD: "Climate Shadow",
    correctOption: "C",
    definition: "A major upgrade to a building to dramatically improve energy efficiency, comfort, and emissions reduction.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Picture this: choosing audio calls instead of video meetings is a form of ........?",
    optionA: "Internal Carbon Pricing",
    optionB: "Green Lashing",
    optionC: "Digital Sobriety",
    optionD: "Closed Loop",
    correctOption: "C",
    definition: "Using digital tools more efficiently and less often to reduce energy use and environmental impact.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "A company assessing both its water use and how droughts might affect its business uses double materiality.",
    optionA: "Emissions Trading",
    optionB: "End-of-life Scenario",
    optionC: "Biophilia",
    optionD: "Double Materiality Assessment",
    correctOption: "D",
    definition: "Looking at how environmental/social issues affect a company and how the company affects the environment/society.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Consider this scenario: turning plastic bottles into carpet fibers is ........?",
    optionA: "Climate Shadow",
    optionB: "Downcycling",
    optionC: "Avoided Emissions",
    optionD: "Environmental Impact Assessment (EIA)",
    correctOption: "B",
    definition: "Recycling materials into products of lower quality or value.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Take this example: the steel in a building has ........ from mining and processing.",
    optionA: "Closed Loop",
    optionB: "Biophilic Design",
    optionC: "Blackwater",
    optionD: "Embedded Carbon",
    correctOption: "D",
    definition: "The carbon emissions created in making a product—from raw materials to manufacturing.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Here's how it plays out: it takes about 1,800 gallons of water to produce one pound of beef— this is ........?",
    optionA: "Blue Financial Instruments",
    optionB: "Embedded Water",
    optionC: "Emissions Trading",
    optionD: "Green Cloud",
    correctOption: "B",
    definition: "The hidden water used to produce goods or services.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "A corporate sustainability report disclosing emissions in all three Scopes to provide transparency.",
    optionA: "Double Materiality Assessment",
    optionB: "Emissions Trading",
    optionC: "Green Hushing",
    optionD: "Scopes of Emission",
    correctOption: "D",
    definition: "A classification of greenhouse gas emissions into Scope 1, 2, 3, and sometimes 4, providing a comprehensive framework for measuring and managing corporate emissions.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "A company that emits less than its allowance can sell its surplus to another company exceeding its cap.",
    optionA: "Emissions Trading",
    optionB: "Embedded Carbon",
    optionC: "Biogenic Carbon Emissions",
    optionD: "Digital Sobriety",
    correctOption: "A",
    definition: "A market-based system where companies can buy or sell allowances for emitting certain amounts of greenhouse gases, promoting cost-effective reductions.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "A plastic bottle is assumed to be recycled in 50% of cases.",
    optionA: "Feed-in Tariff",
    optionB: "Agrichar",
    optionC: "End-of-life Scenario",
    optionD: "Embedded Water",
    correctOption: "C",
    definition: "Assumptions or models about how a product is treated at the end of its useful life, including recycling, landfill, or incineration.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Here's a real-world case: conducting an ........ before constructing a hydroelectric dam.",
    optionA: "Environmental Impact Assessment (EIA)",
    optionB: "Biophilia",
    optionC: "Green Hushing",
    optionD: "Avoided Emissions",
    correctOption: "A",
    definition: "A formal process used to predict environmental consequences of proposed developments before they proceed.",
    level: "DIFFICULT",
    batch: 2,
  },
  {
    text: "Households receiving payments for solar power fed into the national grid.",
    optionA: "Anthropogenic Climate Change",
    optionB: "Closed Loop",
    optionC: "Feed-in Tariff",
    optionD: "Cradle to Gate",
    correctOption: "C",
    definition: "A policy mechanism where governments guarantee payments to individuals or companies for renewable electricity they generate and feed into the grid.",
    level: "DIFFICULT",
    batch: 2,
  },
  // --- Batch 3 (13 questions) ---
  {
    text: "Unsustainable palm oil plantations clearing rainforest.",
    optionA: "End-of-life Scenario",
    optionB: "Forest Risk Commodity",
    optionC: "Scopes of Emission",
    optionD: "Closed Loop",
    correctOption: "B",
    definition: "Products linked to deforestation, like palm oil, soy, beef, and timber.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "Methane is 25 times more powerful at warming the planet than CO₂.",
    optionA: "Avoided Emissions",
    optionB: "Global Warming Potential (GWP)",
    optionC: "Cradle to Gate",
    optionD: "End-of-life Scenario",
    correctOption: "B",
    definition: "A way to compare how much heat different greenhouse gases trap compared to carbon dioxide.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "A company stores data on servers powered by renewable energy.",
    optionA: "Net Zero",
    optionB: "Green Cloud",
    optionC: "Closed Loop",
    optionD: "Biogenic Carbon Emissions",
    correctOption: "B",
    definition: "Using online data storage and services in a way that reduces energy use and emissions.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "A company uses recycled materials but doesn’t advertise it for fear of backlash.",
    optionA: "Biophilia",
    optionB: "Feed-in Tariff",
    optionC: "Green Hushing",
    optionD: "Agflation",
    correctOption: "C",
    definition: "When companies stay quiet about their green actions to avoid public criticism.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "A company is criticized for using recyclable packaging while still working on improving other areas.",
    optionA: "Positive Screening",
    optionB: "Green Lashing",
    optionC: "Biophilic Design",
    optionD: "Cradle to Gate",
    correctOption: "B",
    definition: "When people criticize companies for their green actions, even when they are trying to do better.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "A chocolate company planting trees on farms where cocoa is grown.",
    optionA: "Deep Retrofit",
    optionB: "Green Hushing",
    optionC: "Insetting",
    optionD: "Product Carbon Footprint",
    correctOption: "C",
    definition: "When a company reduces emissions within its own value chain, often by supporting nature-based solutions.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "Charging departments internally for their CO₂ emissions to push them to reduce energy use.",
    optionA: "Anthropogenic Climate Change",
    optionB: "Internal Carbon Pricing",
    optionC: "Agflation",
    optionD: "Closed Loop",
    correctOption: "B",
    definition: "When a company puts its own price on carbon emissions to encourage cleaner decisions.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "Ghana committing to reduce its emissions by 20% by 2030.",
    optionA: "Green Lashing",
    optionB: "Global Warming Potential (GWP)",
    optionC: "Nationally Determined Contributions (NDCS)",
    optionD: "Scopes of Emission",
    correctOption: "C",
    definition: "Countries’ plans to cut emissions and adapt to climate change under the Paris Agreement.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "An ethical fund refusing to invest in oil companies.",
    optionA: "Carbon Sequestration",
    optionB: "Carbon Offsetting",
    optionC: "Negative Screening",
    optionD: "Double Materiality Assessment",
    correctOption: "C",
    definition: "An investment approach that excludes companies involved in harmful activities, like tobacco or fossil fuels.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "Picture this: a business achieving ........ by reducing its emissions and investing in verified carbon removal projects like reforestation.",
    optionA: "Net Zero",
    optionB: "Biophilic Design",
    optionC: "Agflation",
    optionD: "Anthropogenic Removals",
    correctOption: "A",
    definition: "The state where an entity’s greenhouse gas emissions are balanced by an equivalent amount of emissions being removed from the atmosphere, resulting in no net increase in atmospheric GHG levels.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "An investment fund focusing only on companies with high ESG ratings or sustainability certifications.",
    optionA: "Positive Screening",
    optionB: "Blue Financial Instruments",
    optionC: "Anthropogenic Removals",
    optionD: "End-of-life Scenario",
    correctOption: "A",
    definition: "An investment approach where companies or sectors with strong environmental, social, and governance (ESG) performance are actively selected for investment.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "Calculating the carbon footprint of a T-shirt, including cotton farming, manufacturing, shipping, and consumer use.",
    optionA: "Green Cloud",
    optionB: "Product Carbon Footprint",
    optionC: "Negative Screening",
    optionD: "Decarbonisation",
    correctOption: "B",
    definition: "The total greenhouse gas emissions associated with the life cycle of a product, from raw material extraction to disposal or recycling.",
    level: "DIFFICULT",
    batch: 3,
  },
  {
    text: "Transforming old shipping pallets into stylish furniture.",
    optionA: "Positive Screening",
    optionB: "Upcycling",
    optionC: "Biogenic Carbon Emissions",
    optionD: "Carbon Sequestration",
    correctOption: "B",
    definition: "The creative reuse of waste materials or products to create new, higher-quality items, extending product lifecycles and reducing waste.",
    level: "DIFFICULT",
    batch: 3,
  },
];
