// Auto-generated from the SusTerm Dictionary PDF — Easy set.
// Examples are rephrased (not just blanked verbatim) into fresh scenario
// framings, with the term hashed out as "........" and turned into a
// question when the blank lands at the end. `definition` is shown after a
// wrong answer. Split into batches so a session isn't 50+ questions long.
import { Option, Level } from "@prisma/client";

export const susTermEasyQuestions: {
  text: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: Option;
  definition: string;
  level: Level;
  batch: number;
}[] = [
  // --- Batch 1 (15 questions) ---
  {
    text: "Picture this: farmers planting drought-resistant crops because rainfall patterns are changing is a good example of ........ to climate change.",
    optionA: "Base Year Emissions",
    optionB: "Carbon Footprint",
    optionC: "Adaptation",
    optionD: "Bluewashing",
    correctOption: "C",
    definition: "Adaptation means changing our behaviour, environment, or systems to deal with the current or expected effects of climate change. Instead of stopping climate change (mitigation), adaptation is about getting ready for it and reducing the harm it can cause.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Here's a real-world case: when factories release smoke, and cars emit exhaust gases into the atmosphere, they create ........ that can cause asthma and other diseases.",
    optionA: "Air Pollution",
    optionB: "Active Transport",
    optionC: "Carbon Credit",
    optionD: "Climate Risk",
    correctOption: "A",
    definition: "Air pollution happens when harmful gases, dust, or chemicals are released into the air, making it dirty and unsafe to breathe.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Consider this scenario: a power plant that switches from burning coal to using solar panels is performing ........ because it lowers the amount of carbon dioxide it releases into the air.",
    optionA: "Adaptation Strategies",
    optionB: "Abatement",
    optionC: "Carbon Market",
    optionD: "Carbon Intensity",
    correctOption: "B",
    definition: "Abatement means taking action to reduce or remove harmful pollution, especially greenhouse gases like carbon dioxide, from the atmosphere.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Think about it this way: a company like Apple might say: \"We aim to cut our total carbon emissions by 60% by 2030 compared to 2019 levels.\" This is an ........ because it is a fixed goal, no matter how much the company grows.",
    optionA: "Scope 4 Emissions",
    optionB: "Climate Refugee",
    optionC: "Absolute Target",
    optionD: "Active Transport",
    correctOption: "C",
    definition: "An absolute target is a fixed goal to reduce total greenhouse gas emissions by a specific number or percentage, within a certain timeframe.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Take this example: instead of driving 2 kilometers to work, a person rides a bicycle every day. That is ........, it improves health and cuts pollution!",
    optionA: "Climate Risk",
    optionB: "Carbon Footprint",
    optionC: "Active Transport",
    optionD: "Climate Refugee",
    correctOption: "C",
    definition: "Active transport is moving from place to place using your own physical energy, like walking, biking, running, or even skating, instead of using motorized transport like cars or buses.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Here's how it plays out: a coastal city like Miami building stronger sea walls and raising roads to protect against sea-level rise is using ........?",
    optionA: "Adaptation Strategies",
    optionB: "Climate Mitigation",
    optionC: "Transition Plan",
    optionD: "Alternative Energy",
    correctOption: "A",
    definition: "Adaptation strategies are plans or actions that communities, governments, and businesses create to adjust to the impacts of climate change.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "A situation like this comes up often: a rich country with strong healthcare, emergency services, and infrastructure (like Japan) has a high ........ to respond quickly after a typhoon, while a poor country might struggle more.",
    optionA: "Air Quality Index (AQI)",
    optionB: "Climate Justice",
    optionC: "Adaptive Capacity",
    optionD: "Climate Refugee",
    correctOption: "C",
    definition: "Adaptive capacity is the ability of people, communities, businesses, or countries to adjust to the effects of climate change and deal with damage.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "In China, the \"Great Green Wall\" project is planting millions of trees in dry areas to stop desert expansion and absorb more carbon from the atmosphere.",
    optionA: "Climate Refugee",
    optionB: "Adaptive Capacity",
    optionC: "Afforestation",
    optionD: "Climate Risk",
    correctOption: "C",
    definition: "Afforestation is the planting of new forests in places where there were no forests before. It is done to absorb carbon dioxide, restore ecosystems, and fight climate change.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Consider this scenario: an ........ of 50 means good air quality.",
    optionA: "Air Quality Index (AQI)",
    optionB: "Carbon Credit",
    optionC: "Biofuel",
    optionD: "Blue Carbon",
    correctOption: "A",
    definition: "The Air Quality Index (AQI) is a scale that shows how polluted or clean the air is.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Think about it this way: solar panels, wind turbines, and hydropower dams are examples of ........ systems that provide electricity without burning fossil fuels.",
    optionA: "Adaptation Strategies",
    optionB: "Blue Carbon",
    optionC: "Climate Refugee",
    optionD: "Alternative Energy",
    correctOption: "D",
    definition: "Alternative energy is energy produced from sources other than fossil fuels (like coal, oil, or gas).",
    level: "EASY",
    batch: 1,
  },
  {
    text: "If a factory produced 5,000 tons of CO₂ emissions in its base year, it will compare future emissions reductions to this 5,000-ton starting point.",
    optionA: "Carbon Sink",
    optionB: "Climate Risk",
    optionC: "Climate Scenario Analysis",
    optionD: "Base Year Emissions",
    correctOption: "D",
    definition: "Base year emissions are the total greenhouse gas emissions that an organization or country recorded during its selected base year. These emissions serve as a reference point for setting and measuring future climate goals.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Picture this: a cardboard box left outdoors will eventually rot and return to the soil because it is ........?",
    optionA: "Geothermal Energy",
    optionB: "Carbon Positive",
    optionC: "Biodegradable",
    optionD: "Biogas",
    correctOption: "C",
    definition: "Biodegradable means that a substance can break down naturally by bacteria, fungi, or other living organisms into harmless parts without causing damage to the environment.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Here's a real-world case: city buses that run on ........ produce less air pollution than those running on traditional diesel.",
    optionA: "Desertification",
    optionB: "Eco-anxiety",
    optionC: "Climate Refugee",
    optionD: "Biodiesel",
    correctOption: "D",
    definition: "Biodiesel is a clean-burning alternative fuel made from renewable sources like vegetable oils, animal fats, or recycled restaurant grease.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Consider this scenario: the Great Barrier Reef is home to thousands of species of fish, corals, and marine life, showcasing rich ........?",
    optionA: "Biodiversity",
    optionB: "Carbon Capture and Storage (CCS)",
    optionC: "Digital Carbon Footprint",
    optionD: "Waste-to-energy (WTE)",
    correctOption: "A",
    definition: "Biodiversity is the variety of living organisms on Earth, including plants, animals, bacteria, and fungi. It covers the differences within species, between species, and across ecosystems, and is essential for a healthy, functioning planet.",
    level: "EASY",
    batch: 1,
  },
  {
    text: "Think about it this way: producing bio-based plastics from corn or sugarcane instead of oil is part of the growing ........?",
    optionA: "Cradle to Grave",
    optionB: "Afforestation",
    optionC: "Base Year Emissions",
    optionD: "Bioeconomy",
    correctOption: "D",
    definition: "The bioeconomy is an economy where biological resources like plants, animals, and microbes are used to produce food, materials, and energy sustainably.",
    level: "EASY",
    batch: 1,
  },
  // --- Batch 2 (15 questions) ---
  {
    text: "Take this example: a power plant that burns wood chips from forestry residues to produce electricity is using ........?",
    optionA: "Scope 1 Emissions",
    optionB: "Air Quality Index (AQI)",
    optionC: "Bioenergy",
    optionD: "Bioplastics",
    correctOption: "C",
    definition: "Bioenergy is renewable energy produced from biological sources such as plants, agricultural waste, wood, and animal manure. It can be used to generate electricity, produce heat, or fuel vehicles. Unlike fossil fuels, bioenergy sources can be replenished over time.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Buses in some cities use biodiesel made from used cooking oil as a cleaner fuel alternative.",
    optionA: "Voluntary Carbon Market (VCM)",
    optionB: "Adaptation Strategies",
    optionC: "Biofuel",
    optionD: "Carbon Sink",
    correctOption: "C",
    definition: "Biofuel refers to liquid, gas, or solid fuels derived from biomass, including plant and animal materials. It serves as an alternative to fossil fuels and is commonly used in transportation and energy generation. Types include biodiesel, bioethanol, and biogas.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Here's a case worth knowing: a community heating system that burns wood pellets to provide warmth to homes is using ........ energy.",
    optionA: "Carbon Intensity",
    optionB: "Carbon Capture and Storage (CCS)",
    optionC: "Greenwashing",
    optionD: "Biomass",
    correctOption: "D",
    definition: "Biomass refers to any organic material derived from plants, animals, or microorganisms that can be used as a source of energy.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Picture this: a small farm installs a ........ digester to process cow manure and generate gas for cooking and lighting.",
    optionA: "Biogas",
    optionB: "Adaptation Strategies",
    optionC: "Alternative Energy",
    optionD: "Biodegradable",
    correctOption: "A",
    definition: "Biogas is a mixture of methane and carbon dioxide produced by the breakdown of organic matter (like food waste or animal manure) in the absence of oxygen, usually in a digester. It can be used for cooking, heating, or electricity.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Some supermarkets use bioplastic bags that break down more easily in the environment than conventional plastic bags.",
    optionA: "Adaptive Capacity",
    optionB: "Carbon Positive",
    optionC: "Carbon Footprint",
    optionD: "Bioplastics",
    correctOption: "D",
    definition: "Bioplastics are plastics made from renewable sources like corn starch, sugarcane, or potato starch.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "A situation like this comes up often: protecting mangrove forests in Indonesia helps trap ........ and prevents the release of large amounts of CO₂ into the atmosphere.",
    optionA: "Absolute Target",
    optionB: "Blue Carbon",
    optionC: "Adaptive Capacity",
    optionD: "Climate Scenario Analysis",
    correctOption: "B",
    definition: "Blue carbon refers to carbon stored in coastal and marine ecosystems such as mangroves, seagrasses, and salt marshes. These ecosystems absorb and store significant amounts of CO₂, helping to mitigate climate change.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Picture this: a seafood brand markets its products as “sustainably caught” without having any certification, engaging in ........?",
    optionA: "Cradle to Grave",
    optionB: "Bluewashing",
    optionC: "Carbon Emissions",
    optionD: "Alternative Energy",
    correctOption: "B",
    definition: "Bluewashing refers to companies or organizations making exaggerated or false claims about their ocean-friendly or marine conservation efforts to appear environmentally responsible.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Here's a real-world case: a company participates in a ........ by purchasing and depositing certified carbon credits from reforestation projects, which it can later use to offset its emissions or trade in voluntary carbon markets",
    optionA: "Carbon Positive",
    optionB: "Transition Plan",
    optionC: "Afforestation",
    optionD: "Carbon Bank",
    correctOption: "D",
    definition: "A carbon bank is a system, platform, or mechanism where carbon credits are stored, traded, or managed. These banks act as intermediaries, enabling organizations, governments, or individuals to deposit, hold, or invest in carbon credits, which represent the reduction or removal of greenhouse gas emissions from the atmosphere. Carbon banks help streamline the carbon credit market by providing transparency, standardization, and trust, ensuring that credits are verified and accounted for properly. They also support long-term carbon offset strategies by allowing entities to plan for future carbon neutrality goals.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Consider this scenario: a coal power plant uses ........ to trap carbon from its smokestacks and inject it into deep rock formations.",
    optionA: "Adaptation Strategies",
    optionB: "Carbon Capture and Storage (CCS)",
    optionC: "Carbon Positive",
    optionD: "Bioplastics",
    correctOption: "B",
    definition: "CCS is a technology that captures CO₂ emissions from industrial sources and stores them underground, preventing them from entering the atmosphere.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Think about it this way: a company that exceeds its emissions limit can buy ........ from a forest restoration project to offset its pollution.",
    optionA: "Carbon Credit",
    optionB: "Just Transition",
    optionC: "Carbon Positive",
    optionD: "Biofuel",
    correctOption: "A",
    definition: "A carbon credit is a certificate that allows the holder to emit one ton of CO₂. These can be bought or sold in carbon markets, supporting Emission reduction projects.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Take this example: driving a petrol car or using electricity from coal-fired plants causes ........?",
    optionA: "Carbon Emissions",
    optionB: "Biodiversity",
    optionC: "Carbon Capture and Storage (CCS)",
    optionD: "Circular Economy",
    correctOption: "A",
    definition: "The release of carbon, especially carbon dioxide into the air, mostly from burning fossil fuels.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Here's how it plays out: a person who frequently flies and eats a lot of meat will have a larger ........ than someone who walks and eats mostly plant-based foods.",
    optionA: "Carbon Footprint",
    optionB: "Circular Economy",
    optionC: "Bioplastics",
    optionD: "Redd+ (REDUCING Emissions from Deforestation and Forest DEGRADATION)",
    correctOption: "A",
    definition: "The total amount of greenhouse gases a person, company, or product causes, measured in CO₂e.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Picture this: a factory that emits 2 tons of CO₂ for every $1,000 of products it makes has a high ........?",
    optionA: "Just Transition",
    optionB: "Carbon Intensity",
    optionC: "Bioeconomy",
    optionD: "Scope 3 Emissions",
    correctOption: "B",
    definition: "The amount of carbon emissions per unit of something—like per dollar earned or per kilowatt of energy.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "A company that emits less than its limit can sell its extra allowances to another company that is over its limit.",
    optionA: "Geothermal Energy",
    optionB: "Climate Scenario Analysis",
    optionC: "Carbon Bank",
    optionD: "Carbon Market",
    correctOption: "D",
    definition: "A system where companies can buy and sell carbon credits to meet emission goals.",
    level: "EASY",
    batch: 2,
  },
  {
    text: "Think about it this way: a company that captures CO₂ through tree planting and emits very little may be considered ........?",
    optionA: "Bioeconomy",
    optionB: "Adaptation Strategies",
    optionC: "Carbon Negative",
    optionD: "Carbon Capture and Storage (CCS)",
    correctOption: "C",
    definition: "When a person, product, or company removes more carbon dioxide from the air than it emits.",
    level: "EASY",
    batch: 2,
  },
  // --- Batch 3 (15 questions) ---
  {
    text: "Take this example: a company emits 1,000 tons of CO₂ but plants enough trees to absorb 1,000 tons, making it ........?",
    optionA: "Bluewashing",
    optionB: "Biodiesel",
    optionC: "Biodiversity",
    optionD: "Carbon Neutrality",
    correctOption: "D",
    definition: "When total carbon emissions are balanced by removing or offsetting an equal amount of CO₂ from the atmosphere.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Here's how it plays out: a green building that creates more clean energy than it uses may be called “.........”",
    optionA: "Desertification",
    optionB: "Carbon Positive",
    optionC: "Carbon Bank",
    optionD: "Carbon Neutrality",
    correctOption: "B",
    definition: "Often used to mean the same as “carbon negative”—removing more CO₂ than is emitted—but can be confusing because the word “positive” usually means adding CO₂.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Here's a case worth knowing: forests and oceans are major ........ that help slow down climate change.",
    optionA: "Adaptation Strategies",
    optionB: "Offsetting",
    optionC: "Scope 3 Emissions",
    optionD: "Carbon Sink",
    correctOption: "D",
    definition: "A natural or artificial system that absorbs more CO₂ than it emits.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Picture this: a company can buy ........ online to offset their emissions in a transparent, traceable way.",
    optionA: "Carbon Token",
    optionB: "Offsetting",
    optionC: "Just Transition",
    optionD: "Adaptation Strategies",
    correctOption: "A",
    definition: "A digital asset (often using blockchain) that represents a carbon credit or emission reduction.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Here's a real-world case: in a ........, a company might design furniture that can be easily taken apart and reused.",
    optionA: "Alternative Energy",
    optionB: "Air Pollution",
    optionC: "Climate Risk",
    optionD: "Circular Economy",
    correctOption: "D",
    definition: "An economic model that focuses on reusing, repairing, recycling, and sharing products and materials instead of throwing them away.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Consider this scenario: advocating for poor coastal communities to get support after flooding is a matter of ........?",
    optionA: "Cradle to Grave",
    optionB: "Scope 4 Emissions",
    optionC: "Climate Scenario Analysis",
    optionD: "Climate Justice",
    correctOption: "D",
    definition: "The idea that climate change should be addressed in ways that are fair, especially to vulnerable or poor communities most affected by it.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Expanding public transportation systems reduces the number of private vehicles on the road, cutting down carbon emissions and helping mitigate climate change.",
    optionA: "Climate Justice",
    optionB: "Air Quality Index (AQI)",
    optionC: "Climate Mitigation",
    optionD: "Alternative Energy",
    correctOption: "C",
    definition: "Actions taken to reduce or prevent the release of greenhouse gases into the atmosphere, aiming to slow down global warming and climate change.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Take this example: families leaving coastal villages due to sea-level rise are considered ........?",
    optionA: "Just Transition",
    optionB: "Air Quality Index (AQI)",
    optionC: "Carbon Token",
    optionD: "Climate Refugee",
    correctOption: "D",
    definition: "A person who is forced to leave their home due to extreme climate events like floods, droughts, or rising sea levels.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Here's how it plays out: a farm facing more frequent droughts due to climate change is experiencing a ........?",
    optionA: "Biofuel",
    optionB: "Air Pollution",
    optionC: "Climate Risk",
    optionD: "Biodiversity",
    correctOption: "C",
    definition: "Potential negative impacts caused by climate change, including physical risks (like storms) and transition risks (like new regulations).",
    level: "EASY",
    batch: 3,
  },
  {
    text: "A bank uses scenario analysis to understand how stricter carbon regulations might affect its investments.",
    optionA: "Redd+ (REDUCING Emissions from Deforestation and Forest DEGRADATION)",
    optionB: "Climate Refugee",
    optionC: "Climate Scenario Analysis",
    optionD: "Blue Carbon",
    correctOption: "C",
    definition: "A method of exploring how future climate-related events might affect a business or area under different temperature or policy scenarios.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "A shampoo bottle’s cradle-to-grave footprint includes its plastic production, use, and end in a landfill or recycling plant.",
    optionA: "Carbon Neutrality",
    optionB: "Cradle to Grave",
    optionC: "Climate Scenario Analysis",
    optionD: "Alternative Energy",
    correctOption: "B",
    definition: "Tracking a product’s environmental impact from creation to disposal, including use and waste.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Here's how it plays out: cutting down rainforests for palm oil plantations is ........?",
    optionA: "Deforestation",
    optionB: "Redd+ (REDUCING Emissions from Deforestation and Forest DEGRADATION)",
    optionC: "Air Pollution",
    optionD: "Climate Justice",
    correctOption: "A",
    definition: "The removal of forests, often for farming or development, which contributes to climate change and biodiversity loss.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "A situation like this comes up often: overgrazing by livestock can cause ........ in semi-arid areas.",
    optionA: "Climate Scenario Analysis",
    optionB: "Desertification",
    optionC: "Climate Risk",
    optionD: "Carbon Sink",
    correctOption: "B",
    definition: "The process where fertile land becomes dry and unproductive, often due to deforestation, drought, or poor farming.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Here's a case worth knowing: watching high-definition videos online contributes to your ........?",
    optionA: "Carbon Sink",
    optionB: "Carbon Market",
    optionC: "Circular Economy",
    optionD: "Digital Carbon Footprint",
    correctOption: "D",
    definition: "The greenhouse gas emissions caused by using digital technology like emails, streaming, and data storage.",
    level: "EASY",
    batch: 3,
  },
  {
    text: "Think about it this way: many young people experience ........ about the planet’s future.",
    optionA: "Scope 2 Emissions",
    optionB: "Eco-anxiety",
    optionC: "Wildlife Corridor",
    optionD: "Afforestation",
    correctOption: "B",
    definition: "Worry or fear about environmental problems like climate change.",
    level: "EASY",
    batch: 3,
  },
  // --- Batch 4 (14 questions) ---
  {
    text: "Using underground heat in Iceland to power homes.",
    optionA: "Blue Carbon",
    optionB: "Geothermal Energy",
    optionC: "Eco-anxiety",
    optionD: "Adaptation Strategies",
    correctOption: "B",
    definition: "ergy that comes from heat inside the earth, used to make electricity or heat buildings.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "A brand claims to be eco-friendly but still uses harmful packaging.",
    optionA: "Base Year Emissions",
    optionB: "Biofuel",
    optionC: "Greenwashing",
    optionD: "Afforestation",
    correctOption: "C",
    definition: "When a company gives a false impression of being environmentally friendly.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "A company buying verified carbon offsets to compensate for emissions from employee air travel.",
    optionA: "Offsetting",
    optionB: "Carbon Sink",
    optionC: "Digital Carbon Footprint",
    optionD: "Biodegradable",
    correctOption: "A",
    definition: "A climate strategy where emissions from one source are balanced by reducing or removing emissions elsewhere, usually through purchasing carbon credits.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "Training coal workers for renewable energy jobs.",
    optionA: "Bioenergy",
    optionB: "Carbon Neutrality",
    optionC: "Carbon Sink",
    optionD: "Just Transition",
    correctOption: "D",
    definition: "Ensuring the move to a green economy is fair and supports workers and communities.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "A REDD+ project in the Amazon helping local communities protect forests while receiving financial support for doing so.",
    optionA: "Abatement",
    optionB: "Biodegradable",
    optionC: "Redd+ (REDUCING Emissions from Deforestation and Forest DEGRADATION)",
    optionD: "Carbon Negative",
    correctOption: "C",
    definition: "A UN program encouraging developing countries to reduce emissions from deforestation and forest degradation while promoting conservation, sustainable management of forests, and enhancement of forest carbon stocks.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "Emissions from fuel combustion in company-owned vehicles or boilers.",
    optionA: "Adaptation",
    optionB: "Biofuel",
    optionC: "Scope 1 Emissions",
    optionD: "Carbon Capture and Storage (CCS)",
    correctOption: "C",
    definition: "Direct greenhouse gas emissions from sources owned or controlled by an organization.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "Emissions associated with electricity purchased to power a manufacturing plant.",
    optionA: "Scope 2 Emissions",
    optionB: "Abatement",
    optionC: "Bioenergy",
    optionD: "Waste-to-energy (WTE)",
    correctOption: "A",
    definition: "Indirect greenhouse gas emissions from the generation of purchased electricity, steam, heating, or cooling consumed by an organization.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "Emissions from the production of purchased goods, employee commuting, and product disposal.",
    optionA: "Bluewashing",
    optionB: "Adaptation",
    optionC: "Biodegradable",
    optionD: "Scope 3 Emissions",
    correctOption: "D",
    definition: "All other indirect emissions that occur in a company’s value chain, including upstream and downstream activities.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "A solar panel company claiming avoided emissions when its customers switch from fossil fuels to solar energy.",
    optionA: "Scope 4 Emissions",
    optionB: "Deforestation",
    optionC: "Biomass",
    optionD: "Carbon Sink",
    correctOption: "A",
    definition: "Also referred to as avoided emissions, these are emissions reductions outside a company’s value chain as a result of its products or services.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "Smart meters and sensors used by utilities to balance energy supply and demand in real-time.",
    optionA: "Scope 3 Emissions",
    optionB: "Biofuel",
    optionC: "Smart Grid",
    optionD: "Adaptation Strategies",
    correctOption: "C",
    definition: "An advanced energy grid system that uses digital technology to monitor, manage, and optimize electricity delivery, enhancing efficiency and integrating renewable energy.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "A utility company’s plan to phase out coal by 2030 and invest in renewable energy.",
    optionA: "Transition Plan",
    optionB: "Carbon Emissions",
    optionC: "Abatement",
    optionD: "Climate Refugee",
    correctOption: "A",
    definition: "A strategic roadmap detailing how an organization will shift towards net-zero emissions or climate resilience, including interim targets and actions.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "A tech company buying carbon credits to offset its data center emissions by supporting reforestation projects.",
    optionA: "Greenwashing",
    optionB: "Blue Carbon",
    optionC: "Just Transition",
    optionD: "Voluntary Carbon Market (VCM)",
    correctOption: "D",
    definition: "A market where organizations and individuals voluntarily buy carbon credits to offset their emissions, supporting projects that reduce or remove greenhouse gases.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "Incineration plants that generate electricity from household waste.",
    optionA: "Deforestation",
    optionB: "Waste-to-energy (WTE)",
    optionC: "Greenwashing",
    optionD: "Climate Scenario Analysis",
    correctOption: "B",
    definition: "Technologies that convert non-recyclable waste into usable forms of energy, such as electricity, heat, or fuel.",
    level: "EASY",
    batch: 4,
  },
  {
    text: "Highway overpasses built for animals to cross roads safely.",
    optionA: "Wildlife Corridor",
    optionB: "Greenwashing",
    optionC: "Scope 2 Emissions",
    optionD: "Eco-anxiety",
    correctOption: "A",
    definition: "A protected route that allows animals to move between habitats safely, supporting biodiversity and genetic diversity.",
    level: "EASY",
    batch: 4,
  },
];
